'use client';
import { useState } from 'react';
import { formatPrice, tripTypeLabel } from '@/lib/utils';
export default function PricingManager({initial,lookups}:{initial:any[];lookups:any}){const [rows,setRows]=useState(initial); const [msg,setMsg]=useState(''); const [f,setF]=useState<any>({tripType:'GROUP_TRANSPORT',departureCityIds:[],destinationCityIds:[],transportCompanyId:'',vehicleTypeId:'',pricePerPassenger:0,isActive:true});
 function toggle(k:string,id:string){const arr=f[k]||[]; setF({...f,[k]:arr.includes(id)?arr.filter((x:string)=>x!==id):[...arr,id]})}
 async function save(e:React.FormEvent){e.preventDefault(); setMsg(''); const r=await fetch('/api/admin/pricing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)}); const j=await r.json(); if(!r.ok){setMsg(j.message||'حدث خطأ');return} setRows(j.rows); setMsg('تم حفظ الأسعار بنجاح')}
 async function del(id:string){if(!confirm('حذف السعر؟'))return; const r=await fetch('/api/admin/pricing?id='+id,{method:'DELETE'}); const j=await r.json(); if(r.ok)setRows(j.rows)}
 return <div><h1 className="mb-6 text-3xl font-black text-navy">إدارة الأسعار</h1><form onSubmit={save} className="card mb-6 grid gap-5 p-6 lg:grid-cols-3"><label><span className="label">نوع الرحلة</span><select className="input" value={f.tripType} onChange={e=>setF({...f,tripType:e.target.value,transportCompanyId:'',vehicleTypeId:''})}><option value="GROUP_TRANSPORT">نقل جماعي</option><option value="PRIVATE_VEHICLE">سيارة خاصة</option></select></label><label><span className="label">سعر الراكب الواحد</span><input className="input" type="number" value={f.pricePerPassenger} onChange={e=>setF({...f,pricePerPassenger:e.target.value})}/></label><label><span className="label">الحالة</span><select className="input" value={String(f.isActive)} onChange={e=>setF({...f,isActive:e.target.value==='true'})}><option value="true">مفعل</option><option value="false">مخفي</option></select></label><Box title="مدن الانطلاق" items={lookups.departures} checked={f.departureCityIds} onToggle={(id)=>toggle('departureCityIds',id)}/><Box title="مدن الوصول" items={lookups.destinations} checked={f.destinationCityIds} onToggle={(id)=>toggle('destinationCityIds',id)}/>{f.tripType==='GROUP_TRANSPORT'?<label><span className="label">شركة النقل</span><select className="input" value={f.transportCompanyId} onChange={e=>setF({...f,transportCompanyId:e.target.value})}><option value="">اختر الشركة</option>{lookups.companies.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>:<label><span className="label">نوع السيارة</span><select className="input" value={f.vehicleTypeId} onChange={e=>setF({...f,vehicleTypeId:e.target.value})}><option value="">اختر السيارة</option>{lookups.vehicles.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<div className="lg:col-span-3"><button className="btn-primary">حفظ وإنشاء كل التركيبات</button>{msg&&<span className="mr-4 font-bold text-green-700">{msg}</span>}</div></form><div className="card overflow-auto"><table className="w-full min-w-[900px]"><thead><tr><th className="table-th">من</th><th className="table-th">إلى</th><th className="table-th">نوع الرحلة</th><th className="table-th">الشركة / السيارة</th><th className="table-th">سعر الراكب</th><th className="table-th">الحالة</th><th className="table-th">الإجراءات</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td className="table-td">{x.departureCity.name}</td><td className="table-td">{x.destinationCity.name}</td><td className="table-td">{tripTypeLabel(x.tripType)}</td><td className="table-td">{x.transportCompany?.name||x.vehicleType?.name}</td><td className="table-td">{formatPrice(x.pricePerPassenger)}</td><td className="table-td">{x.isActive?'مفعل':'مخفي'}</td><td className="table-td"><button className="btn-light text-red-600" onClick={()=>del(x.id)}>حذف</button></td></tr>)}</tbody></table></div></div>}
function Box({title,items,checked,onToggle}:{title:string;items:any[];checked:string[];onToggle:(id:string)=>void}){return <div className="rounded-3xl border border-slate-200 p-4"><b className="mb-3 block text-navy">{title}</b><div className="grid gap-2">{items.map(x=><label key={x.id} className="flex items-center gap-2"><input type="checkbox" checked={checked.includes(x.id)} onChange={()=>onToggle(x.id)}/>{x.name}</label>)}</div></div>}
