'use client';
import { useState } from 'react';
type Row={id:string;name:string;isActive:boolean;sortOrder?:number;logoUrl?:string|null};
export default function SimpleCrud({title,endpoint,initial,hasSort=false,hasLogo=false}:{title:string;endpoint:string;initial:Row[];hasSort?:boolean;hasLogo?:boolean}){
 const [rows,setRows]=useState<Row[]>(initial); const [form,setForm]=useState<any>({name:'',isActive:true,sortOrder:0,logoUrl:''}); const [editing,setEditing]=useState<string|null>(null); const [msg,setMsg]=useState('');
 async function save(e:React.FormEvent){e.preventDefault(); setMsg(''); const method=editing?'PUT':'POST'; const res=await fetch(endpoint,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:editing})}); const j=await res.json(); if(!res.ok){setMsg(j.message||'حدث خطأ');return} setRows(j.rows); setEditing(null); setForm({name:'',isActive:true,sortOrder:0,logoUrl:''});}
 async function del(id:string){ if(!confirm('هل تريد الحذف؟'))return; const res=await fetch(endpoint+'?id='+id,{method:'DELETE'}); const j=await res.json(); if(!res.ok){setMsg(j.message||'لا يمكن الحذف');return} setRows(j.rows); }
 function edit(x:Row){setEditing(x.id); setForm({name:x.name,isActive:x.isActive,sortOrder:x.sortOrder||0,logoUrl:x.logoUrl||''})}
 return <div><h1 className="mb-6 text-3xl font-black text-navy">{title}</h1><form onSubmit={save} className="card mb-6 grid gap-4 p-5 md:grid-cols-4"><label><span className="label">الاسم</span><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{hasSort&&<label><span className="label">الترتيب</span><input className="input" type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})}/></label>}{hasLogo&&<label><span className="label">رابط الشعار</span><input className="input" value={form.logoUrl} onChange={e=>setForm({...form,logoUrl:e.target.value})}/></label>}<label><span className="label">الحالة</span><select className="input" value={String(form.isActive)} onChange={e=>setForm({...form,isActive:e.target.value==='true'})}><option value="true">مفعل</option><option value="false">مخفي</option></select></label><div className="flex items-end gap-2"><button className="btn-primary">{editing?'تحديث':'إضافة'}</button>{editing&&<button type="button" className="btn-light" onClick={()=>{setEditing(null);setForm({name:'',isActive:true,sortOrder:0,logoUrl:''})}}>إلغاء</button>}</div>{msg&&<p className="md:col-span-4 text-red-600">{msg}</p>}</form><div className="card overflow-hidden"><table className="w-full min-w-[700px]"><thead><tr><th className="table-th">الاسم</th>{hasSort&&<th className="table-th">الترتيب</th>}<th className="table-th">الحالة</th><th className="table-th">الإجراءات</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td className="table-td font-bold">{x.name}</td>{hasSort&&<td className="table-td">{x.sortOrder}</td>}<td className="table-td">{x.isActive?'مفعل':'مخفي'}</td><td className="table-td"><button onClick={()=>edit(x)} className="btn-light ml-2">تعديل</button><button onClick={()=>del(x.id)} className="btn-light text-red-600">حذف</button></td></tr>)}</tbody></table></div></div>
}
